Hw02 express
DanielOsadchenko/nodejs-homework-REST-API pull request #1
Opened 2023-01-24 04:51 UTC by DanielOsadchenko

Completed tasks

2023-01-25 19:08 UTC, Eastvarga requested changes
Добре, але є зауваження

2023-01-25 19:08 UTC, Eastvarga commented on models/contacts.js
> +  console.table(contacts);
А консолі навіщо, не по ТЗ

2023-01-25 19:08 UTC, Eastvarga commented on routes/api/contacts.js
> +  email: Joi.string().email(),
де забули необхідне поле пошти?

2023-01-25 19:08 UTC, Eastvarga commented on routes/api/contacts.js
> +  const { error, value } = schema.validate(req.body);
Валідацію треба винести до окремого мідлвару

2023-01-25 19:08 UTC, Eastvarga commented on routes/api/contacts.js
> +  const { error, value } = schema.validate(req.body);
теж саме

2023-01-26 18:20 UTC, DanielOsadchenko commented on models/contacts.js
> +  console.table(contacts);
+

2023-01-26 18:20 UTC, DanielOsadchenko commented on routes/api/contacts.js
> +  email: Joi.string().email(),
+

2023-01-26 18:20 UTC, DanielOsadchenko commented on routes/api/contacts.js
> +  const { error, value } = schema.validate(req.body);
+

2023-01-26 18:20 UTC, DanielOsadchenko commented on routes/api/contacts.js
> +  const { error, value } = schema.validate(req.body);
+

2023-01-26 19:17 UTC, Eastvarga requested changes
Потрібно дещо привести до більш гарного вигляду, та щоб легше читався код

2023-01-26 19:17 UTC, Eastvarga commented on routes/api/contacts.js
> +router.post("/", async (req, res, next) => {
Ось що з Вами робити.
router.post("/", createContactValidation, createContactController);
сподіваюсь патерн зрозумілий?
Винесіть схуму валідації у окремій файл схем валідації,
а мідлвар валідації у окремий файл мідлварів валідації
сонтролері в окремий файл контролерів
потім їх імпортуєте у файл раутів і все красиво та зрозуміло
А ще б не забули врапер для обробки помилок промісів, а то зараз у Вас помилки промісів не обробляються

2023-01-28 17:19 UTC, Eastvarga requested changes
Непогано, але є ще зауваження

2023-01-28 17:19 UTC, Eastvarga commented on middlewares/validation.js
> +        }
Зайве - для цього у вас є схема та валідація схеми

2023-01-28 17:19 UTC, Eastvarga commented on models/contacts/patch.js
> +        phone: phone ?? oldPhone,
name: name | | oldName, простіше,
 і да - краще Вам ще пошукати більш простішу логіку - це не зауваження

2023-01-28 17:19 UTC, Eastvarga commented on models/contacts/remove.js
> +    const [removedContact] = contacts.splice(index, 1);
не використовуйте методи котрі мутують масив, це антипатерн.

2023-01-28 17:19 UTC, Eastvarga commented on models/contacts/update.js
> +    };
не вірно - бо якщо name=undefined у вас contacts[index].name буде undefined

2023-01-30 16:09 UTC, DanielOsadchenko commented on models/contacts/patch.js
> +        phone: phone ?? oldPhone,
+

2023-01-30 16:15 UTC, DanielOsadchenko commented on middlewares/validation.js
> +        }
++

2023-01-30 16:44 UTC, DanielOsadchenko commented on models/contacts/remove.js
> +    const [removedContact] = contacts.splice(index, 1);
++

2023-01-30 16:54 UTC, DanielOsadchenko commented on models/contacts/update.js
> +    };
update  використовує метод put і має всі поля (name, phone, email) обов'язковими до заповнення. Тобто ці поля обов'язково прийдут з клієнта

2023-01-30 19:22 UTC, Eastvarga commented on models/contacts/update.js
> +    };
Чи розумієте Ви принципи не зв'язності коду? Ваш метод оновлення повинен знати тільки те що йому приходить - він універсальний, отже повинен вміти оновлювати як увесь об'єкт так і одне його поле, Чи ви для цього завдання збираєтесь іншу функцію створити?

2023-01-30 19:26 UTC, Eastvarga approved these changes

2023-01-30 19:26 UTC, merged